### PR TITLE
Fix Error Handling in config-file.c

### LINKED ISSUE #23: Segmentation fault caused by "config.conf" file
Hi,
when using the rauc-hawkbit-updater, we get a SIGSEGV. Segmentation Fault.
We noticed, that the updater crashes while trying to get the data from the “config.conf” file.
It seems, that the Boolean variables in the “config.conf” file are not parsed correctly and because of that the comments, which are declared with a “#” on the same line, are being ignored as comments and written into the variables.

Did anyone have the same Problem?

Thanks.

### PR DESCRIPTION
**Pull request by ejoerns**
This fixes the handling of GError's in config-file.c in many different ways.

As a result of this, no segmentation faults caused by unset errors should be triggered anymore and parsing of broken configuration should return valid error messages.

Fixes #23
Replaces #24

### CODE REVIEW

File: src/config-file.c [hunk 1]
```diff
@@ -76,38 +80,64 @@ static gboolean get_key_bool(GKeyFile *key_file, const gchar* group, const gchar
...
         guint key;
         gsize num_keys;
-        gchar **keys, *value;
+        gchar **keys;
 
         *hash = g_hash_table_new(g_str_hash, g_str_equal);
-        keys = g_key_file_get_keys(key_file, group, &num_keys, &error);
+        keys = g_key_file_get_keys(key_file, group, &num_keys, error);
+        if (keys == NULL)
+                return FALSE;
```
Comment (Raphexion) [inline src/config-file.c:118]: Do we need a g_set_error here (above return) since we return FALSE?

File: src/config-file.c [hunk 2]
```diff
@@ -76,38 +80,64 @@ static gboolean get_key_bool(GKeyFile *key_file, const gchar* group, const gchar
...
-                value = g_key_file_get_value(key_file,
-                                             group,
-                                             keys[key],
-                                             &error);
+                gchar *value = g_key_file_get_value(key_file,
+                                                    group,
+                                                    keys[key],
+                                                    error);
+                if (value == NULL)
+                        return FALSE;
```
Comment (Raphexion) [inline src/config-file.c:134]: Do we need a g_set_error here (above return) since we return FALSE?

File: src/config-file.c (hunk 1 above)
Comment (ejoerns) [reply src/config-file.c:118]: No, as `error` is set by `g_key_file_get_keys()` in this case.

File: src/config-file.c (hunk 2 above)
Comment (ejoerns) [reply src/config-file.c:134]: same as above
